# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{butterfly}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Thomas Duerr"]
  s.date = %q{2010-11-03}
  s.description = %q{Butterfly is a very simple and easy extensible code generator for common every day projects.}
  s.email = %q{thomduerr@gmail.com}
  s.executables = ["butterfly", "butterfly.html"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "README.md",
     "Rakefile",
     "bin/butterfly",
     "bin/butterfly.html",
     "butterfly.gemspec",
     "heroku_generators/sinatra/USAGE",
     "heroku_generators/sinatra/sinatra_generator.rb",
     "heroku_generators/static/static_generator.rb",
     "heroku_generators/static/templates/README.md",
     "heroku_generators/static/templates/config.ru",
     "heroku_generators/static/templates/public/css/main.css",
     "heroku_generators/static/templates/public/index.html",
     "heroku_generators/static/templates/public/js/app.js",
     "jquery_generators/plugin/USAGE",
     "jquery_generators/plugin/plugin_generator.rb",
     "jquery_generators/plugin/templates/demo.html",
     "jquery_generators/plugin/templates/js/jquery.plugin_name.js",
     "lib/butterfly.rb",
     "lib/options.rb"
  ]
  s.homepage = %q{http://github.com/thomd/butterfly/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{a life-enhancing code generator for everyday use}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rubigen>, [">= 1.5.5"])
      s.add_runtime_dependency(%q<git>, [">= 1.2.5"])
      s.add_development_dependency(%q<jeweler>, [">= 1.4.0"])
    else
      s.add_dependency(%q<rubigen>, [">= 1.5.5"])
      s.add_dependency(%q<git>, [">= 1.2.5"])
      s.add_dependency(%q<jeweler>, [">= 1.4.0"])
    end
  else
    s.add_dependency(%q<rubigen>, [">= 1.5.5"])
    s.add_dependency(%q<git>, [">= 1.2.5"])
    s.add_dependency(%q<jeweler>, [">= 1.4.0"])
  end
end

