source "http://rubygems.org"

# All Environment
gem "haml", "3.0.23"
gem "sinatra", "1.1.0"
gem "dm-core", "1.0.2"
gem "dm-validations", "1.0.2"
gem "dm-sqlite-adapter", "1.0.2"
gem "dm-migrations", "1.0.2"
gem "data_objects", "0.10.2"
gem "do_sqlite3", "0.10.2"

# Development Environment
group :development do
#  gem 'thin', "1.2.7"
end
